version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - db  
  
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "dockerDb_123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
      - "1434:1434"